title: Federated Learning CFP Deadlines
description: Countdowns to Federated Learning CFP deadlines
author: Marcello Maugeri

domain: "fl-deadlines.github.io"
baseurl: ""

twitter_hashtag: federatedlearning
github_username: fl-deadlines
github_repo: fl-deadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
